# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
#solc_version = '0.8.19'
auto_detect_solc = true
optimizer_runs = 1_000
remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/=node_modules/@uniswap/",
]

[rpc_endpoints]
bsctest = "https://data-seed-prebsc-2-s2.binance.org:8545/"
bsc = "https://bsc-dataseed.binance.org/"

[etherscan]
bsctest = { key = "${ETHERSCAN_API_KEY}" }
bsc = { key = "${ETHERSCAN_API_KEY}" }
